mutation

diff --git a/.github/workflows/wingsdk-mutation.yml b/.github/workflows/wingsdk-mutation.yml
--- a/.github/workflows/wingsdk-mutation.yml
+++ b/.github/workflows/wingsdk-mutation.yml
@@ -20,14 +20,9 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
-    env:
-      CI: "true"
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.ref }}
-          repository: ${{ github.event.repository.full_name }}
       - name: Login to private npm registry
         run: npm config set @winglang:registry https://npm.pkg.github.com && npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
       - name: Setup Node.js
@@ -48,70 +43,26 @@ jobs:
         name: Find mutations
         run: |-
           git add .
-          git diff --staged --patch --exit-code > .repo.patch || echo "::set-output name=self_mutation_happened::true"
-      - if: steps.self_mutation.outputs.self_mutation_happened
-        name: Upload patch
+          git diff --staged --patch --exit-code || echo "::set-output name=self_mutation_happened::true"
+      - name: Upload patch
+        if: steps.self_mutation.outputs.self_mutation_happened
         uses: actions/upload-artifact@v2
         with:
           name: .repo.patch
           path: libs/wingsdk/.repo.patch
-
-      - name: Fail build on mutation
-        if: steps.self_mutation.outputs.self_mutation_happened
-        run: |-
-          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
-          cat .repo.patch
-          exit 1
-      - name: Upload artifact
-        uses: actions/upload-artifact@v2.1.1
-        with:
-          name: wingsdk-build-artifact
-          path: libs/wingsdk/dist
-  self-mutation:
-    needs: build
-    runs-on: ubuntu-latest
-    if: always() && needs.build.outputs.self_mutation_happened
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.ref }}
-          repository: ${{ github.event.repository.full_name }}
-      - name: Download patch
-        uses: actions/download-artifact@v3
-        with:
-          name: .repo.patch
-          path: ${{ runner.temp }}
-      - name: Apply patch
-        run: '[ -s ${{ runner.temp }}/.repo.patch ] && git apply ${{ runner.temp }}/.repo.patch || echo "Empty patch. Skipping."'
       - name: Set git identity
+        if: steps.self_mutation.outputs.self_mutation_happened
         run: |-
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
       - name: Push changes
-        run: |2-
-            git add .
-            git commit -s -m "chore: self mutation"
-            git push origin HEAD:${{ github.event.ref }}
-  package-js:
-    needs: build
-    runs-on: ubuntu-latest
-    permissions: {}
-    if: "! needs.build.outputs.self_mutation_happened"
-    steps:
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 16.x
-      - name: Download build artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: wingsdk-build-artifact
-          path: libs/wingsdk/dist
-      - name: Prepare Repository
-        run: mv dist .repo && npm config set @winglang:registry https://npm.pkg.github.com && npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
-      - name: Install Dependencies
-        run: cd .repo && npm ci
-      - name: Create js artifact
-        run: cd .repo && npx projen package:js
-      - name: Collect js Artifact
-        run: mv .repo/dist dist
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          git add .
+          git commit -s -m "chore: self mutation"
+          git push origin HEAD:${{ github.event.ref }}
+      - name: Fail build on mutation
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Files were changed during build (see build log)."
+          exit 1
